class Joke(val text: String, val image: String? = null)

val jokes = listOf(
        Joke("Prediction:\nThere will be a minor baby boom in 9 months,\nand then one day in 2033, we shall whitness the rise of the QUARANTEENS."),
        Joke("If you need 144 rolls of toilet paper for a 14 day quarantine,\nyou probably should have been seeing a Doctor long before COVID-19."),
        Joke("The worst thing about corona?\nCOVID-19 looks like a Jira issue."),
        Joke("What is Happiness?\nWhen you work at a bank and two guys with masks come in\nbut they're just robbing the place."),
        Joke("Quarantine diary\n\nDay 1: I have stocked up on enough non-perishable food and supplies to last me for months, maybe years, so that I can remain in isolation for as long as it takes to see out this pandemic.\n\nDay 1 + 45 minutes: I am in the supermarket because I wanted a Twix."),
        Joke("Kid: Hey mum, when is this corona virus thing gonna be over?\nMum: Just shut up and eat your toilet paper."),
        Joke("Chuck Norris has been exposed to the Coronavirus.\nThe virus is now in quarantine for a month."),
        Joke("Some people aren't shaking hands because of the Corona virus.\nI'm not shaking hands because everyone is out of toilet paper."),
        Joke("", "olympia.jpg"),
        Joke("", "clean-ass.jpg"),
        Joke("", "tom.jpg"),
        Joke("", "chipotle.jpg"),
        Joke("", "learning.jpg"),
        Joke("", "corona-case.jpg"),
        Joke("", "young.jpg"),
        Joke("", "charmin.jpg"),
        Joke("", "tarantino.jpg"),
        Joke("", "apocalypse.jpg"),
        Joke("", "paper-crisis.jpg"),
        Joke("", "titanic.jpg"),
        Joke("", "cry.jpg"),
        Joke("", "god.jpg"),
        Joke("Even panic buyers have some honor.", "panic-buyer.jpg"),
        Joke("", "homework.jpg"),
        Joke("", "lockdown.jpg"),
        Joke("", "spock.jpg"),
        Joke("", "shining.jpg"),
        Joke("", "hands.jpg"),
        Joke("", "ebola.jpg"),
        Joke("", "mask.jpg"),
        Joke("", "bigfoot.jpg"),
        Joke("", "buy-god.jpg"),
        Joke("", "touch-face.jpg"),
        Joke("", "suite.jpg"),
        Joke("", "flirt.jpg"),
        Joke("Social distancing in the 1750s.", "old-distance.jpg"),
        Joke("", "borg.jpg")
)
